### ISSUE TITLE
Example yields wrong SVG

### ISSUE THREAD

**Issue by noxer** [frankbraun/asciiart#1]
When doing the following:

`go get github.com/frankbraun/asciiart/util/cmd/aaexample`
`go get github.com/frankbraun/asciiart/cmd/aa2svg`
`aaexample | aa2svg > diagram.svg`

I get the file: [diagram.svg.zip](https://github.com/frankbraun/asciiart/files/135823/diagram.svg.zip) (had to zip it in order to upload it to github). Any idea how that happened?

Cheers
Tim

edit: The generated AST maches the one in the readme.

**Comment by frankbraun** [comment]
I probably didn't make that clear enough: `aaexample` is just an example on how to use the ASCII art parser API and it uses it to print an ASCII tree of the ASCII art structure.

If you want to render ASCII art as SVG you have to call `aa2svg` directly with the ASCII art text file (it then generates the AST internally and uses it to create the SVG output). To generate the SVG for the example call:

`aa2svg < $GOPATH/src/github.com/frankbraun/asciiart/templates/exampleart.tmpl > example.svg`

In `$GOPATH/src/github.com/frankbraun/asciiart/svg/testdata` you can find more example text files to render.

**Comment by noxer** [comment]
Yes, thank you. I thought it was a two step process.
