### ISSUE TITLE
Formating bug

### ISSUE THREAD

**Issue by noxer** [frankbraun/asciiart#2]
When using a '<' right before text, the first letter of the text is deleted.
[issue.txt](https://github.com/frankbraun/asciiart/files/136307/issue.txt) -> aa2svg magic -> [issue.svg.zip](https://github.com/frankbraun/asciiart/files/136309/issue.svg.zip)

The '<' should probably be ignored.

**Comment by frankbraun** [comment]
Thanks for reporting this! It is now fixed. However, I don't like the idea of silently dropping characters which appear in the input file. I chose to add the '<' character to the text instead. The AST then looks like this for your example:

```
grid 9 3
  rect 0.5 0.5 8 2 null
    textline 2.5 1.5 <Text
```

Does that make sense to you?

**Comment by noxer** [comment]
Thats perfect. Thanks!
